language: node_js
node_js:
- '16.20.2'
env:
  global:
  - MATTERMOST_CHANNEL=publication
  # REGISTRY_TOKEN slug=edf editor=cozy space=cozy_ccc
  - secure: OlcOmFYiGcTnBAOu0LubukryP+WD5EOL+WBTEGquNZTJ07U7EqtnVaO4KDysB6ltiiwaPpFKr2I3YmR8aGlBWzrlpOTOGvG9qdAnbEur6b7//VkPFwsQ306m+uXE/UgJK2hUT4O/hcXnRL51JF3FESvKiW72Bgw/i4ZTAYP+fYYFHX1P2zvKo9lqci4GZq7oqg4h3Mj0CBBYE4/S2DHtTU0ihSGxp4SHJiEZzwyybMDVXYufbxn82op9WHqDVB7WuxLUjupZsYWPXlv4/jlz12bAD75ffzPtADEiWa2XYV5ZFu3rjpEKCE+C2MzCGkFPKIR4BihewNHFTf0/vQDpZwHRH+lVmnxCMEDkLgw1vnOgRtIDkNWTIkRe1WUu0+63VR07Neri1vkTctImOgzcNRP3UOCJ71eUkDb4ugj0lROZU+P7gfuf/vrvY6gRZkX3tqcbhCiPAWIZtp1k0YOUi/ts6qJ6ZRREPd4vfvCF7yUBCbWbFOxlo9l7yRvsFdLgPWuCes/qpKO1OcPTwvXpAwpf/gYQ6WkCvKA19HymOrlCyb3ZfVjJzGwo633T8u1LTy+ou06dNAL+mMgqsROfAuEwvp5KWiphiveq/4eMnZ1IckxkaVMsVHHU84Ywd/QfUAm09AeN+fa1qUJFPJOXByAlxtviARaPF+oCsOXEazo=
  # MATTERMOST_HOOK_URL
  - secure: hSJiMEYEFwVclFXTQSb0h/QBSx3hu/PjTqEwCaeHTKAYbdwMdpDaYCIHvAPrZQYqxFx3t3bfp7O9+tGVW6UO7OPrkOZSR7FtzF4urcKSFyQn8BNAZUKnXvvEW5JFUfLKt1KDHocurcEvqMK92q3BQsHiInjCS2Fj/t1tKArLo9ggpMIH2lIlppti+L5F6l3VRGOKHuQvZvxP4NmJ4PEq/0elU0R+XLjvEgaRh2NNDENtdOauywGYug8Ew5mxggzPDs09MefvqFmo96SGMOnOVXDG8zjBOdq+IKMUUOIOSCw2xh0r5+fdPZY3wU1afGnkoAIdWM1cFPGcwPgT9CGhrP8ecWZXvJlgc3BxsII6TWTPvDrKc6SBmWFQ/E7bh9V2X3vBA1c87O2X5EHGWAA2sKPCo0aYKNNyvw6LeH8rlLuHWGsJVXYslyswploU4I9+31xS8bgqKMaZQsCWSmbOFyQ66Vjut8Cfklni7Eb23ffAg8aOOXJMqFNSOslkPNQkglxcmp/Wr8ZM+QJVXkNqk+/98FigihRVFFUiha9WHILr+nz/MjdC4nazGXFQlVuc2xtNIqjnF12FdgWAqARi7v4QDVhwC6aYsi5rJPdW4riYLz4J6NtoiJ90D8i9XbN4MR+dqgk7PmvWwLZzsXrpRCszgGK3okAVsrRB8f5A45w=
cache:
  yarn: true
  directories:
  - node_modules
branches:
  except:
  - build
  - build-debug
script:
- yarn lint
- yarn build
deploy:
- provider: script
  skip-cleanup: true
  script: DEPLOY_BRANCH=build yarn deploy && yarn cozyPublish --space cozy_ccc
  on:
    branch: master
- provider: script
  skip-cleanup: true
  script: DEPLOY_BRANCH=build yarn deploy && yarn cozyPublish --postpublish mattermost --space cozy_ccc
  on:
    tags: true
before_install:
- openssl aes-256-cbc -K $encrypted_8ebb1ef83f64_key -iv $encrypted_8ebb1ef83f64_iv
  -in github_deploy_key.enc -out /tmp/github_deploy_key -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/github_deploy_key
- ssh-add /tmp/github_deploy_key
after_deploy:
- rm /tmp/github_deploy_key
- ssh-add -D
