language: node_js
node_js:
- '16.20.2'
env:
  global:
  - MATTERMOST_CHANNEL=publication
  # REGISTRY_TOKEN slug=edf editor=cozy
  - secure: H/Qk8PAVeP6/ccUMsmvBW3XPnP05Zb+lOIieoheHla4MOewv7oNOCGgijMKjKE4fEVKmBRTIcSeax7HEQtWRnedt9K3H5esMpfFt3P3W5AHrThz0l+MUuH9oBZYKq4EY8fpedq7WUT10tmjqXcqz28OCQ4gzL3Ecv/mLNBaHrB9DdGAc2E0RS42TisJdnpQOEaOZkuskaORgqmJwgkWyL+6EWTabozAuOj9TUW7ogUTC0AWOdNoh1u44M9mSP/3mq1cjnzRhoLsWrJW+mGJhmcpOntHlZxKzgWRLvalE3Tk2XCwUTyFocIyWzrkElw1bTD0grtJ3wuciqSTShtadz1n76WO94VDFxttDELz5avUTGizncRyqeEYzf+EExqNcLM46x0Cbwt4lTgavCA/yljBkAo9ReaNeEFH/p+vgVkcCW86jflHBpMxhhb2haWYJKEq62u6r/IkbCfnmtdpvZdMFYkP3inXtqw9HuhXjeNtDYEVhNGZgScqVamngYGvdSafJlwnPkItFWNJC8+erlWutEdJOXuiKKQqjQpROQ6Hb01HVickiVTH4rngg8QKdTdGvvAqqMUowda6Cu7VAcfCqIC0cGMbBc43SqTqUcWhsBu1buvAjzJEajZ46RaJnpvDs4xqF+JuDXND3gxctmBmPjVfGr49f1Jv/MBWEUVc=
  # MATTERMOST_HOOK_URL
  - secure: hSJiMEYEFwVclFXTQSb0h/QBSx3hu/PjTqEwCaeHTKAYbdwMdpDaYCIHvAPrZQYqxFx3t3bfp7O9+tGVW6UO7OPrkOZSR7FtzF4urcKSFyQn8BNAZUKnXvvEW5JFUfLKt1KDHocurcEvqMK92q3BQsHiInjCS2Fj/t1tKArLo9ggpMIH2lIlppti+L5F6l3VRGOKHuQvZvxP4NmJ4PEq/0elU0R+XLjvEgaRh2NNDENtdOauywGYug8Ew5mxggzPDs09MefvqFmo96SGMOnOVXDG8zjBOdq+IKMUUOIOSCw2xh0r5+fdPZY3wU1afGnkoAIdWM1cFPGcwPgT9CGhrP8ecWZXvJlgc3BxsII6TWTPvDrKc6SBmWFQ/E7bh9V2X3vBA1c87O2X5EHGWAA2sKPCo0aYKNNyvw6LeH8rlLuHWGsJVXYslyswploU4I9+31xS8bgqKMaZQsCWSmbOFyQ66Vjut8Cfklni7Eb23ffAg8aOOXJMqFNSOslkPNQkglxcmp/Wr8ZM+QJVXkNqk+/98FigihRVFFUiha9WHILr+nz/MjdC4nazGXFQlVuc2xtNIqjnF12FdgWAqARi7v4QDVhwC6aYsi5rJPdW4riYLz4J6NtoiJ90D8i9XbN4MR+dqgk7PmvWwLZzsXrpRCszgGK3okAVsrRB8f5A45w=
cache:
  yarn: true
  directories:
  - node_modules
branches:
  except:
  - build
  - build-debug
script:
- yarn lint
- yarn build
deploy:
- provider: script
  skip-cleanup: true
  script: DEPLOY_BRANCH=build yarn deploy && yarn cozyPublish
  on:
    branch: master
- provider: script
  skip-cleanup: true
  script: DEPLOY_BRANCH=build yarn deploy && yarn cozyPublish --postpublish mattermost
  on:
    tags: true
before_install:
- openssl aes-256-cbc -K $encrypted_8ebb1ef83f64_key -iv $encrypted_8ebb1ef83f64_iv
  -in github_deploy_key.enc -out /tmp/github_deploy_key -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/github_deploy_key
- ssh-add /tmp/github_deploy_key
after_deploy:
- rm /tmp/github_deploy_key
- ssh-add -D
